### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by techtonik** [lepture/mistune-contrib#3]
Are there any plans to package those? It is kind of hard to setup dependencies for HTML TOC extension,

**Comment by techtonik** [comment]
@lepture pip fails to install `mistune-contrib` now. This is the log from Heroku https://github.com/gratipay/inside.gratipay.com/issues/410#issuecomment-158487528

**Comment by lepture** [comment]
@techtonik Ok. Published to PyPI.

**Comment by techtonik** [comment]
@lepture thanks! You saved my day. =)

I was going to create a separate "virtual machine" for Heroku just to get this working. :+1:
